# Generated by Django 4.2 on 2026-03-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_description', models.TextField()),
                ('weight_kg', models.FloatField()),
                ('pickup_state', models.CharField(max_length=100)),
                ('pickup_city', models.CharField(max_length=100)),
                ('drop_state', models.CharField(max_length=100)),
                ('drop_city', models.CharField(max_length=100)),
                ('quoted_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
