# Generated by Django 4.2 on 2026-03-27 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsrequest',
            name='logistics_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logisticsrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_requests', to='orders.order'),
        ),
    ]
