# Generated by Django 4.2 on 2026-03-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_farmerprofile_latitude_farmerprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
