# Generated by Django 4.2 on 2026-03-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_logisticsprofile_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/buyer/'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='certificates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/farmer/'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='taluka',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='village',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='logisticsprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/logistics/'),
        ),
        migrations.AddField(
            model_name='user',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account_holder',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='passbook_photo',
            field=models.ImageField(blank=True, null=True, upload_to='passbooks/'),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='business_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('store', 'Store'), ('buyer', 'Buyer')], max_length=50),
        ),
    ]
