# Generated by Django 4.2 on 2026-03-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pickup_state', models.CharField(blank=True, max_length=100)),
                ('pickup_city', models.CharField(blank=True, max_length=100)),
                ('drop_state', models.CharField(blank=True, max_length=100)),
                ('drop_city', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('logistics_pending', 'Logistics Pending'), ('logistics_assigned', 'Logistics Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('completed', 'Completed')], default='confirmed', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
