# Generated by Django 4.2 on 2026-03-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=200)),
                ('variety', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('market', models.CharField(blank=True, max_length=200)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_date', models.DateField()),
                ('unit', models.CharField(default='Quintal', max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('commodity', 'state', 'market', 'price_date')},
            },
        ),
    ]
