export const CATEGORIES = [
  { value: 'vegetables', label: 'Vegetables' },
  { value: 'fruits', label: 'Fruits' },
  { value: 'grains', label: 'Grains' },
  { value: 'spices', label: 'Spices' },
]

export const PRODUCT_OPTIONS = {
  vegetables: [
    'Tomato',
    'Onion',
    'Potato',
    'Cabbage',
    'Cauliflower',
    'Carrot',
    'Beetroot',
    'Spinach',
    'Coriander',
    'Brinjal',
    'Capsicum',
    'Green Chilli',
    'Cucumber',
    'Pumpkin',
    'Bottle Gourd',
    'Ladyfinger',
    'Peas',
    'Radish',
  ],
  fruits: [
    'Banana',
    'Apple',
    'Mango',
    'Orange',
    'Grapes',
    'Pomegranate',
    'Papaya',
    'Watermelon',
    'Muskmelon',
    'Guava',
    'Pineapple',
    'Lemon',
    'Sweet Lime',
    'Strawberry',
    'Pear',
    'Litchi',
  ],
  grains: [
    'Wheat',
    'Rice',
    'Maize',
    'Barley',
    'Bajra',
    'Jowar',
    'Ragi',
    'Oats',
    'Millet Mix',
    'Chickpea',
    'Lentils',
    'Pigeon Pea',
    'Green Gram',
    'Black Gram',
  ],
  spices: [
    'Turmeric',
    'Cumin',
    'Coriander Seeds',
    'Mustard Seeds',
    'Fenugreek',
    'Cardamom',
    'Black Pepper',
    'Clove',
    'Cinnamon',
    'Dry Red Chilli',
    'Bay Leaf',
    'Fennel',
    'Ajwain',
    'Ginger',
    'Garlic',
  ],
}
