# Generated by Django 4.2.29 on 2026-03-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_city_alter_product_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_available',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
